# Generated by Django 5.2.1 on 2025-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0001_initial'),
    ]

    operations = [
    ]
