# Generated by Django 5.2 on 2025-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer/Producer'), ('buyer', 'Buyer/Retailer'), ('supplier', 'Supplier'), ('logistics', 'Logistics'), ('admin', '')], max_length=20),
        ),
    ]
