# Generated by Django 5.2.1 on 2025-05-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0002_fix_missing_profiles'),
    ]

    operations = [
    ]
