# Generated by Django 5.0.6 on 2025-05-10 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0002_rename_role_user_user_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowtransaction',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['BUYER', 'LOGISTICS']}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['FARMER', 'SUPPLIER']}, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CROP', 'Crops'), ('LIVESTOCK', 'Livestock'), ('EQUIPMENT', 'Equipment'), ('SEEDS', 'Seeds'), ('FERTILIZER', 'Fertilizer'), ('OTHER', 'Other')], default='CROP', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['FARMER', 'SUPPLIER']}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionupdate',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['ADMIN', 'LOGISTICS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
