# Generated by Django 5.2 on 2025-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('dairy', 'Dairy'), ('poultry', 'Poultry'), ('herbs&spices', 'Herbs & Spices')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('piece', 'Piece'), ('dozen', 'Dozen'), ('liter', 'Liter')], max_length=50),
        ),
    ]
