# Generated by Django 5.2.1 on 2025-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0004_alter_buyerprofile_primary_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
