# Generated by Django 5.2.1 on 2025-05-18 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0006_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='delivery_proof',
            field=models.FileField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order Update'), ('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be Ethiopian format: +2517XXXXXXXX, +2519XXXXXXXX, 07XXXXXXXX, or 09XXXXXXXX', regex='^(\\+251[79]\\d{8}|0[79]\\d{8})$')]),
        ),
    ]
