# Generated by Django 5.2.1 on 2025-05-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0007_escrowtransaction_buyer_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
