# Generated by Django 5.2.1 on 2025-05-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0008_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='escrow_transaction',
            new_name='related_transaction',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('REFUND', 'Refund')], max_length=20),
        ),
    ]
