# Generated by Django 5.2.1 on 2025-05-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0009_rename_escrow_transaction_wallettransaction_related_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsprofile',
            name='pickup_location',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Price per kilometer in ETB', max_digits=6),
        ),
        migrations.AddField(
            model_name='logisticsprofile',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Price per kilometer in ETB', max_digits=6),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('logistics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac.product')),
            ],
        ),
    ]
