# Generated by Django 5.2.1 on 2025-05-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0010_logisticsprofile_pickup_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADDIS_ABABA', 'Addis Ababa'), ('DIRE_DAWA', 'Dire Dawa'), ('BAHIR_DAR', 'Bahir Dar'), ('MEKELLE', 'Mekelle'), ('AWASA', 'Awasa'), ('JIMMA', 'Jimma'), ('GONDAR', 'Gondar'), ('NAZRET', 'Nazret'), ('DEBRE_MARKOS', 'Debre Markos'), ('ARBA_MINCH', 'Arba Minch')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='logisticsprofile',
            name='nationwide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='logisticsprofile',
            name='service_areas',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ac.city', verbose_name='Primary Delivery City'),
        ),
        migrations.AddField(
            model_name='logisticsprofile',
            name='service_areas',
            field=models.ManyToManyField(help_text='Select cities you service (select Nationwide for all areas)', related_name='logistics_providers', to='ac.city'),
        ),
    ]
