# Generated by Django 5.2.1 on 2025-05-26 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0013_remove_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ac.deliveryjob'),
        ),
    ]
