# Generated by Django 5.2.1 on 2025-05-26 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0014_notification_delivery_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjob',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
