# Generated by Django 5.2.1 on 2025-05-26 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0015_alter_deliveryjob_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjob',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Estimated pickup time'),
        ),
    ]
