# Generated by Django 5.2.1 on 2025-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0016_alter_deliveryjob_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
