# Generated by Django 5.2.1 on 2025-05-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0020_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='ac_user',
        ),
    ]
