# Generated by Django 5.2.1 on 2025-05-28 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0021_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Updated via F() expressions only!', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
