# Generated by Django 5.2.1 on 2025-05-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0022_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettopuprequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='wallettopuprequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='wallettopuprequest',
            name='status',
        ),
    ]
